### PR TITLE
feat: delete item from list

### LINKED ISSUE #1: feat: delete item from list
Delete items from the board

### PR DESCRIPTION
**Pull request by lucasnevespereira**
Hello @bashbunni I find this cli quite cool, wanted to give it a try and solve issue #1. 
I've implemented a new method `DeleteCurrent()` to delete the selected task when the user types `d`.

I've tested in my machine it works fine, it would be cool to write some tests for it when I have more time 👍🏼 

Let me know if this sounds okay to you 😃

### CODE REVIEW

**Comment by bashbunni** [comment]
Hey @lucasnevespereira, thanks for the PR! 

You're off to a great start. What would be great to see would be: 
- [ ] handling if the list is empty and the user tries to delete an item
- [ ] deleting items in "In Progress" and "Done" lists (it's only deleting in the "To Do" list right now

**Review by bashbunni — CHANGES_REQUESTED** [review]
See previous comment

**Review by lucasnevespereira — COMMENTED** [review]
Hello, in this commit I'm checking if the list of `VisibleItems()` is empty before deleting the task. 
I could also do this the other way around by check if there is an item in `VisibleItems()` and do the delete in the condition body to avoid having two returns in the function. 

Something like:
```
func (m *Model) DeleteCurrent() tea.Msg {
	if len(m.lists[m.focused].VisibleItems()) > 0 {
		selectedTask := m.lists[m.focused].SelectedItem().(Task)
		m.lists[selectedTask.status].RemoveItem(m.lists[m.focused].Index())
	}
	return nil
}
```

**Review by lucasnevespereira — COMMENTED** [review]
Hi @bashbunni, this commit fixes the delete for tasks under "in progress" and "done". Actually, the issue was that these 2 lists were init with tasks with the wrong status.

I've also changed the logic to check an empty list in `DeleteCurrent()` as mentioned in my last comment 😄

**Review by bashbunni — APPROVED** [review]
Looks great! Thank you for your contribution 😄

**Pull request merged**
